services:
  postgres:
    image: postgres:17
    container_name: rent-a-mate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: saig
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rent_a_mate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  object-storage:
    image: rustfs/rustfs:latest
    container_name: rent-a-mate-object-storage
    restart: unless-stopped
    environment:
      RUSTFS_VOLUMES: /data
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: minioadmin
      RUSTFS_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - object_storage_data:/data

volumes:
  postgres_data:
  object_storage_data:
