services:
  postgres:
    image: postgres:17
    container_name: rent-a-mate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: saig
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rent_a_mate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: