import { describe, expect, it } from 'vitest';
import bcrypt from 'bcrypt';
import { PasswordHashService } from './password-hash.service.js';

describe('PasswordHashService', () => {
  it('verifies a password generated by the service', async () => {
    const service = new PasswordHashService();
    const hash = await service.hash('correct horse battery staple');

    await expect(
      service.verify('correct horse battery staple', hash),
    ).resolves.toBe(true);
    await expect(service.verify('wrong password', hash)).resolves.toBe(false);
  });

  it('does not expose the plain password in the generated hash', async () => {
    const service = new PasswordHashService();
    const hash = await service.hash('correct horse battery staple');

    expect(hash).toMatch(/^scrypt\$[^$]+\$[^$]+$/);
    expect(hash).not.toContain('correct horse battery staple');
  });

  it('rejects malformed hashes without throwing', async () => {
    const service = new PasswordHashService();

    await expect(
      service.verify('any password', 'not-a-bcrypt-hash'),
    ).resolves.toBe(false);
  });

  it('continues to verify legacy bcrypt hashes', async () => {
    const service = new PasswordHashService();
    const legacyHash = await bcrypt.hash('legacy password', 12);

    await expect(service.verify('legacy password', legacyHash)).resolves.toBe(
      true,
    );
  });
});
