import { describe, expect, it } from 'vitest';
import { BcryptPasswordService } from './password.service.js';

describe('BcryptPasswordService', () => {
  it('verifies a password generated by the service', async () => {
    const service = new BcryptPasswordService();
    const hash = await service.hash('correct horse battery staple');

    await expect(service.verify('correct horse battery staple', hash)).resolves.toBe(true);
    await expect(service.verify('wrong password', hash)).resolves.toBe(false);
  });

  it('does not expose the plain password in the generated hash', async () => {
    const service = new BcryptPasswordService();
    const hash = await service.hash('correct horse battery staple');

    expect(hash).toMatch(/^\$2[aby]\$\d{2}\$/);
    expect(hash).not.toContain('correct horse battery staple');
  });

  it('rejects malformed hashes without throwing', async () => {
    const service = new BcryptPasswordService();

    await expect(service.verify('any password', 'not-a-bcrypt-hash')).resolves.toBe(false);
  });
});
